[package]
name = "arca-json"
version = "0.7.1" # lock to arca-wallet version
license = "MIT"
authors = [ "Team Second <hello@second.tech>" ]
description = "JSON definitions for the bark APIs"
edition = "2024"

[lib]
name = "bark_json"

[features]
default = ["onchain-bdk"]
onchain-bdk = ["arca-wallet/onchain-bdk", "arca-bitcoin-ext/bdk"]

[dependencies]
# OWN
arca-wallet = { version = "0.7.1", path = "../bark", default-features = false }
arca-lib = { version = "0.7.1", path = "../lib" }
arca-bitcoin-ext = { version = "0.7.1", path = "../bitcoin-ext", default-features = false }

# INTERNAL
serde_json.workspace = true

# EXPORTED
anyhow.workspace = true
bitcoin.workspace = true
serde.workspace = true
humantime.workspace = true
thiserror.workspace = true
chrono.workspace = true

utoipa = { version = "5.4.0", optional = true, features = ["chrono"] }

[dev-dependencies]
serde_json.workspace = true
